### ISSUE TITLE
Erro ao logar na interface do eDemocracia

### ISSUE THREAD

**Issue by alexlopespereira** [eDemocracia/edemocracia#66]
Tenho a aplicacao do eDemocracia na versao da tag 1.2.1. Ao tentar logar com o usuario adminstrador (aquele configurado no docker-compose.yml) a seguinte mensagem de erro é exibida no browser "Ocorreu um erro no servidor, tente novamente em alguns instantes."

E o log do nginx mostra as mensagens abaixo.

democracia_1       | [2018-05-29 12:23:49 +0000] [259] [ERROR] Error handling request
edemocracia_1       | Traceback (most recent call last):
edemocracia_1       |   File "/usr/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 185, in handle_request
edemocracia_1       |     self.log.access(resp, req, environ, request_time)
edemocracia_1       |   File "/usr/lib/python3.6/site-packages/gunicorn/glogging.py", line 343, in access
edemocracia_1       |     (self.cfg.syslog and not self.cfg.disable_access_log_redirection)):
edemocracia_1       |   File "/usr/lib/python3.6/site-packages/gunicorn/config.py", line 62, in __getattr__
edemocracia_1       |     raise AttributeError("No configuration setting for: %s" % name)
edemocracia_1       | AttributeError: No configuration setting for: disable_access_log_redirection

Me pareceu (por este link https://github.com/benoitc/gunicorn/issues/1768) que este é um problema do gunicorn e que já foi corrigido naquela comunidade. Gostaria de saber se vocês tem alguma tag onde este problema já foi corrigido.

**Comment by alexlopespereira** [comment]
Estava usando a branch master do edem-navigation. Se usar a branch fix/edem-without-colab o problema se resolve.
